export type SearchFaq = {
  id: string;
  group: "baslangic" | "kapsam" | "hesaplama" | "dogrulama" | "maliyet" | "urun";
  question: string;
  answer: string;
  ownerUrl: string;
  keywords: string[];
  sourceUrl?: string;
  sourceLabel?: string;
};

const EC = "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism_en";
const EC_GUIDANCE = "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/cbam-legislation-and-guidance_en";
const TR = "https://ticaret.gov.tr/dis-iliskiler/yesil-mutabakat/ab-sinirda-karbon-duzenleme-mekanizmasi";
const TR_FAQ = "https://ticaret.gov.tr/dis-iliskiler/yesil-mutabakat/ab-sinirda-karbon-duzenleme-mekanizmasi/sikca-sorulan-sorular";

export const SEARCH_FAQS: readonly SearchFaq[] = [
  {
    id: "cbam-nedir",
    group: "baslangic",
    question: "CBAM nedir, SKDM ile aynı şey mi?",
    answer: "Evet. CBAM, Carbon Border Adjustment Mechanism; SKDM ise Türkçedeki Sınırda Karbon Düzenleme Mekanizması adıdır. 1 Ocak 2026'dan itibaren kesin dönem uygulanır ve yükümlülük AB'deki yetkili beyan sahibi üzerindedir; Türkiye'deki üretici ise alıcının kullanacağı tesis, üretim ve gömülü emisyon verisini hazırlamak zorundadır.",
    ownerUrl: "/rehber/",
    keywords: ["cbam nedir", "skdm nedir", "cbam türkiye", "sınırda karbon düzenleme mekanizması"],
    sourceUrl: TR,
    sourceLabel: "T.C. Ticaret Bakanlığı — AB SKDM",
  },
  {
    id: "cbam-raporu",
    group: "baslangic",
    question: "CBAM raporu nedir ve Türk ihracatçı ne hazırlamalı?",
    answer: "Türkiye'deki üreticinin pratik ihtiyacı, AB alıcısına tesis ve ürün bazında doğrulanabilir gömülü emisyon verisi vermektir. Bu çalışma; tesis kimliği, CN/GTİP, üretim süreçleri, enerji-yakıt verileri, üretim miktarı, öncül maddeler, izleme planı, hesap izi ve Communication Template çıktısını birlikte ele almalıdır. SKDMHesapla bunu 'AB'ye resmi beyan' olarak değil, alıcıya ve akredite doğrulayıcıya sunulacak denetime hazırlık çalışma dosyası olarak üretir.",
    ownerUrl: "/cbam-hesaplama/",
    keywords: ["cbam raporu", "skdm raporu", "cbam raporu nasıl hazırlanır", "skdm raporu hazırlama"],
    sourceUrl: TR_FAQ,
    sourceLabel: "T.C. Ticaret Bakanlığı — SKDM SSS",
  },
  {
    id: "cbam-hesaplama",
    group: "hesaplama",
    question: "CBAM hesaplama nasıl yapılır?",
    answer: "Önce ürünün 8 haneli CN/GTİP koduyla kapsam kontrolü yapılır. Kapsamdaysa tesisin üretim süreçleri, kaynak akışları, yakıt/elektrik verileri, üretim seviyesi ve kapsam içi öncül maddeleri toplanır. Gömülü emisyon, kesin dönem metodolojisine göre ürünün fonksiyonel birimine bölünerek özgül gömülü emisyona dönüştürülür. Sertifika maliyeti hesabı bunun üzerinde ayrı bir katmandır.",
    ownerUrl: "/cbam-hesaplama/",
    keywords: ["cbam hesaplama", "skdm hesaplama", "cbam hesaplama aracı", "skdm hesaplama aracı"],
    sourceUrl: EC_GUIDANCE,
    sourceLabel: "European Commission — CBAM legislation and guidance",
  },
  {
    id: "cbam-excel",
    group: "urun",
    question: "CBAM Excel dosyası veya Communication Template nedir?",
    answer: "Communication Template, AB Komisyonunun üçüncü ülke tesis operatörünün emisyon verisini AB ithalatçısına iletmesi için yayımladığı Excel çalışma kitabıdır. Tek başına hesaplama yöntemi değildir; hesaplama ve izleme verileri kesin dönem mevzuatına göre hazırlanır, ardından ilgili alanlar şablona aktarılır.",
    ownerUrl: "/cbam-hesaplama/",
    keywords: ["cbam excel", "cbam hesaplama excel", "communication template", "cbam communication template"],
    sourceUrl: EC_GUIDANCE,
    sourceLabel: "European Commission — CBAM guidance",
  },
  {
    id: "kim-sorumlu",
    group: "baslangic",
    question: "CBAM beyanını Türk ihracatçı mı verir?",
    answer: "Hayır. Yıllık CBAM beyanı ve sertifika yükümlülüğü AB'deki yetkili CBAM beyan sahibi veya ilgili gümrük temsilcisi üzerindedir. Türk üretici/ihracatçı, alıcının beyanında kullanacağı tesis ve emisyon verisini sağlamakla operasyonel olarak kritik rol oynar.",
    ownerUrl: "/sss/",
    keywords: ["cbam beyanını kim verir", "skdm sorumlusu kim", "türk ihracatçı cbam beyanı"],
    sourceUrl: TR_FAQ,
    sourceLabel: "T.C. Ticaret Bakanlığı — SKDM SSS",
  },
  {
    id: "hangi-sektorler",
    group: "kapsam",
    question: "Hangi sektörler CBAM / SKDM kapsamında?",
    answer: "Kesin dönemde temel sektör aileleri demir-çelik, alüminyum, çimento, gübre, elektrik ve hidrojendir. Fakat hukuki kapsam kararı sektör adına bakılarak değil, ürünün Annex I kapsamındaki CN koduna göre verilmelidir.",
    ownerUrl: "/rehber/",
    keywords: ["cbam sektörleri", "skdm sektörleri", "cbam kapsamı", "skdm kapsamındaki ürünler"],
    sourceUrl: EC,
    sourceLabel: "European Commission — CBAM",
  },
  {
    id: "gtip-kapsam",
    group: "kapsam",
    question: "GTİP kodum CBAM kapsamında mı?",
    answer: "Kapsam kontrolünün ana girdisi ürün adı değil, 8 haneli CN/GTİP kodudur. Türkiye GTİP'inin ilk 8 hanesi AB CN koduyla eşleştirilerek resmi kapsam listesi kontrol edilmelidir. Ticari ürün adı tek başına hukuki kapsam kararı için yeterli değildir.",
    ownerUrl: "/basla/",
    keywords: ["gtip cbam kapsamı", "gtip skdm", "cbam gtip sorgulama", "skdm gtip sorgulama"],
    sourceUrl: TR_FAQ,
    sourceLabel: "T.C. Ticaret Bakanlığı — SKDM SSS",
  },
  {
    id: "50-ton",
    group: "kapsam",
    question: "CBAM 50 ton muafiyeti nedir?",
    answer: "50 ton de minimis eşiği, tek bir Türk satıcının sevkiyatına göre değil AB tarafındaki ithalatçının ilgili takvim yılındaki toplam CBAM ithalatına göre değerlendirilir. Bu nedenle ihracatçının yalnız kendi tonajına bakarak 'muafım' sonucu çıkarması doğru değildir; alıcıdan yıllık toplam durum teyidi alınmalıdır.",
    ownerUrl: "/cbam-50-ton-muafiyeti/",
    keywords: ["cbam 50 ton", "skdm 50 ton", "cbam 50 ton muafiyeti", "skdm muafiyet"],
    sourceUrl: TR,
    sourceLabel: "T.C. Ticaret Bakanlığı — AB SKDM",
  },
  {
    id: "50-ton-ihracatci",
    group: "kapsam",
    question: "Ben 50 tonun altında ihracat yapıyorum; otomatik olarak muaf mıyım?",
    answer: "Hayır, otomatik sonuç çıkarılamaz. Eşik AB ithalatçısının yıllık toplam CBAM ithalatı üzerinden uygulanır. Aynı alıcının farklı tedarikçilerden yaptığı ithalatlar toplamı eşiği aşabilir. Alıcınızdan de minimis durumunu teyit etmeden dosyayı kapsam dışı kabul etmeyin.",
    ownerUrl: "/cbam-50-ton-muafiyeti/",
    keywords: ["50 ton altı cbam", "50 ton altı skdm", "cbam muaf mıyım"],
    sourceUrl: TR,
    sourceLabel: "T.C. Ticaret Bakanlığı — AB SKDM",
  },
  {
    id: "actual-default",
    group: "hesaplama",
    question: "Gerçek emisyon değeri mi, varsayılan değer mi kullanmalıyım?",
    answer: "Gerçek değer, tesisinizin izleme planı ve üretim verilerinden hesaplanan değerdir ve doğrulama sürecine hazırlanmalıdır. Mevzuatın izin verdiği durumlarda varsayılan değer kullanılabilir; ancak kesin dönemde default values üzerine sektör/yıl bazlı mark-up uygulanabildiği için maliyet etkisi daha yüksek olabilir. Hangi yöntemin uygulanabildiği ürün ve veri durumuna göre sınıflandırılmalıdır.",
    ownerUrl: "/sss/",
    keywords: ["cbam actual values", "cbam default values", "skdm varsayılan değer", "cbam gerçek emisyon"],
    sourceUrl: TR,
    sourceLabel: "T.C. Ticaret Bakanlığı — AB SKDM",
  },
  {
    id: "default-markup",
    group: "hesaplama",
    question: "CBAM varsayılan değer artışı (mark-up) 2026'da ne kadar?",
    answer: "Ticaret Bakanlığının güncel özetine göre 2026-2028 için çoğu ilgili ürün grubunda sırasıyla %10, %20 ve %30 mark-up uygulanır; gübrede oran %1 seviyesinde tutulur. Kullanılan default-value veri setinin güncel sürümü ayrıca kontrol edilmelidir.",
    ownerUrl: "/sss/",
    keywords: ["cbam markup 2026", "cbam varsayılan değer 2026", "skdm default value"],
    sourceUrl: TR,
    sourceLabel: "T.C. Ticaret Bakanlığı — AB SKDM",
  },
  {
    id: "dolayli-emisyon",
    group: "hesaplama",
    question: "Elektrik tüketimi CBAM hesabına girer mi?",
    answer: "Sektöre göre değişir. Güncel kesin dönem özetinde çimento ve gübre için dolaylı emisyonlar hesaba katılır; demir-çelik ve alüminyum için sertifika yükümlülüğünde yalnız doğrudan emisyonlar dikkate alınır. Elektrik verisi yine de veri kalitesi ve dosya bütünlüğü açısından kayıt altında tutulabilir.",
    ownerUrl: "/sss/",
    keywords: ["cbam elektrik emisyonu", "skdm dolaylı emisyon", "cbam indirect emissions"],
    sourceUrl: TR,
    sourceLabel: "T.C. Ticaret Bakanlığı — AB SKDM",
  },
  {
    id: "precursor",
    group: "hesaplama",
    question: "CBAM precursor / öncül madde nedir?",
    answer: "Ürettiğiniz CBAM malının üretiminde kullanılan ve kendisi de kapsam içindeki ara girdidir. Uygun durumda öncül maddenin gömülü emisyonu nihai ürün hesabına taşınır. Bu nedenle yalnız fabrikanın yakıt tüketimini hesaplamak yeterli olmayabilir; tedarikçiden precursor verisi istenmesi gerekir.",
    ownerUrl: "/sozluk/",
    keywords: ["cbam precursor", "skdm öncül madde", "cbam hammadde emisyonu"],
    sourceUrl: EC_GUIDANCE,
    sourceLabel: "European Commission — CBAM guidance",
  },
  {
    id: "dogrulama-zorunlu",
    group: "dogrulama",
    question: "CBAM emisyon raporunu kim doğrular?",
    answer: "Kesin dönem doğrulaması, CBAM kapsamında akredite bağımsız doğrulayıcı tarafından yapılır. SKDMHesapla akredite doğrulama görüşü vermez; doğrulayıcının inceleyebileceği veri, kanıt, izleme planı ve hesap izini hazırlayan self-servis çalışma alanıdır.",
    ownerUrl: "/cbam-dogrulama/",
    keywords: ["cbam doğrulama", "skdm doğrulayıcı", "cbam verifier", "cbam doğrulama kuruluşu"],
    sourceUrl: EC_GUIDANCE,
    sourceLabel: "European Commission — CBAM guidance",
  },
  {
    id: "verifier-registry",
    group: "dogrulama",
    question: "CBAM doğrulayıcı Registry'ye ne zaman kaydolur?",
    answer: "Komisyonun 24 Ağustos 2026 rehberine göre doğrulayıcı önce ilgili ulusal akreditasyon kuruluşundan CBAM akreditasyonunu alır, ardından Registry erişimi için başvurur. Kayıt süreci 1 Eylül 2026'dan önce başlayamaz; akreditasyon sonrasında iki ay içinde kayıt gerekir. Doğrulama raporları Ocak 2027'den itibaren Registry üzerinden düzenlenir.",
    ownerUrl: "/cbam-dogrulama/",
    keywords: ["cbam registry verifier", "cbam doğrulayıcı registry", "1 eylül 2026 cbam"],
    sourceUrl: "https://taxation-customs.ec.europa.eu/news/european-commission-publishes-guidance-cbam-verifiers-and-accreditation-bodies-2026-08-24_en",
    sourceLabel: "European Commission — 24 August 2026 verifier guidance",
  },
  {
    id: "registry-kim",
    group: "dogrulama",
    question: "Türk üretici CBAM Registry'ye kendisi mi beyan verir?",
    answer: "AB ithalatçısının yıllık CBAM beyanı Türk üreticinin sorumluluğu değildir. Registry'de farklı roller ve erişim akışları bulunur. Türk tesis operatörünün ana işi, ithalatçı ve doğrulayıcıya kullanılabilir tesis/emisyon verisini tutarlı şekilde sağlamaktır.",
    ownerUrl: "/sss/",
    keywords: ["cbam registry türkiye", "skdm kayıt sistemi", "cbam registry kim kullanır"],
    sourceUrl: EC,
    sourceLabel: "European Commission — CBAM Registry",
  },
  {
    id: "sertifika-fiyati",
    group: "maliyet",
    question: "CBAM sertifika fiyatı nasıl hesaplanır?",
    answer: "Sertifika fiyatı AB ETS karbon fiyatına bağlıdır. 2026 ithalatları için fiyat, 2026 yılı içinde oluşan ilgili çeyreklik ortalamalara dayanır; sertifika satın alma ve teslim yükümlülüğü AB tarafındadır. Üreticinin gömülü emisyon değeri, ithalatçının kaç sertifikaya ihtiyaç duyacağını belirleyen ana girdilerden biridir.",
    ownerUrl: "/fiyatlandirma/",
    keywords: ["cbam sertifika fiyatı", "skdm maliyeti", "cbam maliyet hesaplama", "karbon vergisi hesaplama"],
    sourceUrl: TR,
    sourceLabel: "T.C. Ticaret Bakanlığı — AB SKDM",
  },
  {
    id: "2026-takvim",
    group: "maliyet",
    question: "2026 CBAM beyanı ve sertifika takvimi nedir?",
    answer: "2026 ithalatlarına ilişkin ilk yıllık beyanın son tarihi 30 Eylül 2027'dir. Ticaret Bakanlığı güncel özetine göre 2026 yılı ithalatlarına ilişkin sertifika satışının Şubat 2027'de başlaması öngörülür. İşletme verisi ise 2026 yılı boyunca izlenip 2027 doğrulamasına hazır tutulmalıdır.",
    ownerUrl: "/sss/",
    keywords: ["cbam 2026", "skdm 2026", "cbam beyan tarihi", "cbam 30 eylül 2027"],
    sourceUrl: TR,
    sourceLabel: "T.C. Ticaret Bakanlığı — AB SKDM",
  },
  {
    id: "karbon-vergisi",
    group: "maliyet",
    question: "CBAM bir karbon vergisi mi?",
    answer: "Günlük dilde 'karbon vergisi' denilse de mekanizma teknik olarak CBAM sertifikalarının satın alınması ve teslimi üzerinden çalışır. Bu nedenle arama ve maliyet hesabında 'CBAM karbon vergisi' ifadesi kullanıcı dili olarak anlaşılabilir; hukuki açıklamada sertifika yükümlülüğü ifadesi tercih edilmelidir.",
    ownerUrl: "/sss/",
    keywords: ["cbam karbon vergisi", "sınırda karbon vergisi", "karbon vergisi hesaplama"],
    sourceUrl: EC,
    sourceLabel: "European Commission — CBAM",
  },
  {
    id: "danisman-zorunlu",
    group: "urun",
    question: "CBAM raporu için danışman tutmak zorunlu mu?",
    answer: "Hayır. Mevzuat Türk üreticinin verisini mutlaka bir danışmana hazırlatma şartı koymaz. Tesis verisi şirket içinde hazırlanabilir veya yazılımla organize edilebilir. Ancak akredite doğrulama gerekiyorsa bu aşama bağımsız ve yetkili doğrulayıcı tarafından yürütülür.",
    ownerUrl: "/cbam-hesaplama/",
    keywords: ["cbam danışmanlık", "skdm danışman zorunlu mu", "cbam raporu kendim hazırlayabilir miyim"],
    sourceUrl: EC_GUIDANCE,
    sourceLabel: "European Commission — CBAM guidance",
  },
  {
    id: "alici-ne-ister",
    group: "urun",
    question: "AB müşterim 'CBAM raporunu gönder' dedi; ne göndermeliyim?",
    answer: "Önce alıcının istediği ürün/CN kapsamını ve hangi dönem verisini talep ettiğini netleştirin. Ardından tesis kimliği, ürün grubu, üretim süreci, faaliyet verileri, öncül maddeler, gömülü emisyon sonucu ve kullanılan yöntem ile kanıt referanslarını hazırlayın. En pratik teslim biçimi, resmi Communication Template alanlarıyla uyumlu ve doğrulayıcıya iz bırakacak bir çalışma paketidir.",
    ownerUrl: "/cbam-hesaplama/",
    keywords: ["müşteri cbam raporu istedi", "ab müşterisi karbon raporu istedi", "cbam raporu gönderme"],
    sourceUrl: TR_FAQ,
    sourceLabel: "T.C. Ticaret Bakanlığı — SKDM SSS",
  },
  {
    id: "kabul",
    group: "urun",
    question: "SKDMHesapla dosyasını alıcım veya doğrulayıcı kabul eder mi?",
    answer: "Sistem resmi kesin dönem veri yapısını ve Communication Template çıktısını hedefler; fakat nihai kabul kararı her zaman alıcıya ve akredite doğrulayıcıya aittir. Yazılımın SHA-256 mührü dosya bütünlüğünü kanıtlar, akredite CBAM doğrulaması yerine geçmez.",
    ownerUrl: "/fiyatlandirma/",
    keywords: ["cbam raporu kabul edilir mi", "skdmhesapla güvenilir mi", "cbam doğrulayıcı kabul"],
  },
  {
    id: "fiyat",
    group: "urun",
    question: "SKDMHesapla ne kadar?",
    answer: "Kapsam kontrolü, veri girişi ve ön kontroller ücretsizdir. Ödeme yalnız mühürlü denetime hazırlık paketini üretmek istediğiniz aşamada alınır. Güncel tek seferlik paket fiyatı 9.900 TL KDV dahildir.",
    ownerUrl: "/fiyatlandirma/",
    keywords: ["cbam raporu fiyatı", "skdm raporu fiyatı", "cbam hesaplama fiyatı"],
  },
] as const;

export const SEARCH_FAQ_GROUPS = [
  { id: "baslangic", label: "CBAM / SKDM başlangıç soruları" },
  { id: "kapsam", label: "Kapsam, GTİP ve 50 ton muafiyeti" },
  { id: "hesaplama", label: "Emisyon hesabı, Excel ve veri" },
  { id: "dogrulama", label: "Doğrulama, akreditasyon ve Registry" },
  { id: "maliyet", label: "Sertifika, takvim ve maliyet" },
  { id: "urun", label: "Türk ihracatçı için pratik uygulama" },
] as const;
