import type { PcfFactorRecord } from "./types";
import { validateFactorRegistry } from "./factor-registry";

/**
 * PUBLIC / REDISTRIBUTION-SAFE FACTOR CATALOG
 *
 * KURAL:
 * - Bu dosyaya kaynaksız sayı girilemez.
 * - Kullanıcıdan genel LCA faktörü serbest sayı olarak alınmaz.
 * - source.nextReviewAt geçmişse resolver faktörü kullanmaz.
 * - Aşağıdaki DEFRA 2025 kayıtları yalnız migration kanıtıdır; 2026 sürümüyle
 *   insan incelemesi yapılarak yenilenmeden üretimde seçilemez.
 */
const RAW_FACTORS: readonly PcfFactorRecord[] = [
  {
    id: "evced-tr-electricity-distribution-2023",
    kind: "electricity",
    labelTr: "Türkiye dağıtım hattı elektrik tüketim faktörü",
    labelEn: "Türkiye distribution-grid electricity consumption factor",
    materialIds: ["electricity-grid"],
    aliases: ["elektrik", "şebeke elektriği", "distribution electricity"],
    geographies: ["TR"],
    activityUnit: "kWh",
    kgCo2ePerActivityUnit: 0.469,
    boundary: "scope2-location-based",
    gwpBasis: "CO2e as published by ETKB EVÇED",
    quality: "official_generic",
    reviewStatus: "approved",
    buyerReadyEligible: true,
    validFrom: "2023-01-01",
    connectionType: "distribution",
    source: {
      publisher: "T.C. Enerji ve Tabii Kaynaklar Bakanlığı - EVÇED",
      title: "Türkiye Elektrik Üretimi ve Elektrik Tüketim Noktası Emisyon Faktörleri",
      version: "ETKB-EVÇED, veri yılı 2023",
      referenceYear: 2023,
      reviewedAt: "2026-08-17",
      nextReviewAt: "2026-12-31",
      sourceUrl: "https://enerji.gov.tr/evced-cevre-ve-iklim-elektrik-uretim-tuketim-emisyon-faktorleri",
      licence: "Kamu yayını; kullanım kapsamı kaynak metniyle birlikte doğrulanır",
      sourceType: "official",
      notes: "Dağıtım hattından bağlı tüketim noktası için 0,469 tCO2e/MWh = 0,469 kgCO2e/kWh.",
    },
    limitations: [
      "Türkiye dağıtım hattından bağlı tüketim noktaları içindir.",
      "Piyasa-temelli yenilenebilir enerji iddiasını otomatik olarak temsil etmez.",
    ],
  },
  {
    id: "evced-tr-electricity-transmission-2023",
    kind: "electricity",
    labelTr: "Türkiye iletim hattı elektrik tüketim faktörü",
    labelEn: "Türkiye transmission-grid electricity consumption factor",
    materialIds: ["electricity-grid"],
    aliases: ["elektrik", "iletim hattı", "transmission electricity"],
    geographies: ["TR"],
    activityUnit: "kWh",
    kgCo2ePerActivityUnit: 0.436,
    boundary: "scope2-location-based",
    gwpBasis: "CO2e as published by ETKB EVÇED",
    quality: "official_generic",
    reviewStatus: "approved",
    buyerReadyEligible: true,
    validFrom: "2023-01-01",
    connectionType: "transmission",
    source: {
      publisher: "T.C. Enerji ve Tabii Kaynaklar Bakanlığı - EVÇED",
      title: "Türkiye Elektrik Üretimi ve Elektrik Tüketim Noktası Emisyon Faktörleri",
      version: "ETKB-EVÇED, veri yılı 2023",
      referenceYear: 2023,
      reviewedAt: "2026-08-17",
      nextReviewAt: "2026-12-31",
      sourceUrl: "https://enerji.gov.tr/evced-cevre-ve-iklim-elektrik-uretim-tuketim-emisyon-faktorleri",
      licence: "Kamu yayını; kullanım kapsamı kaynak metniyle birlikte doğrulanır",
      sourceType: "official",
      notes: "İletim hattından bağlı tüketim noktası için 0,436 tCO2e/MWh = 0,436 kgCO2e/kWh.",
    },
    limitations: [
      "Türkiye iletim hattından bağlı tüketim noktaları içindir.",
      "Piyasa-temelli yenilenebilir enerji iddiasını otomatik olarak temsil etmez.",
    ],
  },
  {
    id: "legacy-defra-2025-aluminium-proxy",
    kind: "material",
    labelTr: "Alüminyum - eski vekil kayıt",
    labelEn: "Aluminium - legacy proxy record",
    materialIds: ["aluminium"],
    aliases: ["alüminyum", "aluminium", "aluminum"],
    geographies: ["GLOBAL_PROXY"],
    activityUnit: "kg",
    kgCo2ePerActivityUnit: 9.1159,
    boundary: "material-production-only",
    gwpBasis: "Legacy source metadata; human re-review required",
    quality: "proxy",
    reviewStatus: "estimate_only",
    buyerReadyEligible: false,
    validFrom: "2025-01-01",
    validTo: "2025-12-31",
    source: {
      publisher: "UK DESNZ / DEFRA",
      title: "Government GHG Conversion Factors for Company Reporting 2025 - Material use",
      version: "2025",
      referenceYear: 2025,
      reviewedAt: "2026-08-17",
      nextReviewAt: "2026-06-30",
      sourceUrl: "https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2025",
      licence: "Open Government Licence v3.0 - exact row/boundary must be rechecked",
      sourceType: "official",
      notes: "Mevcut repo örnek raporundan migrate edilmiştir; 2026 veri setiyle yenilenmeden seçilemez.",
    },
    limitations: [
      "Türkiye üretim koşullarını temsil etmez.",
      "Mevcut repo notunda profil/ekstrüzyon için vekil kullanıldığı belirtilmiştir.",
      "2026 DESNZ veri seti yayımlandığı için tazelik kapısından geçmez.",
    ],
  },
  {
    id: "legacy-defra-2025-glass-generic",
    kind: "material",
    labelTr: "Cam - eski genel kayıt",
    labelEn: "Glass - legacy generic record",
    materialIds: ["glass"],
    aliases: ["cam", "glass"],
    geographies: ["GLOBAL_PROXY"],
    activityUnit: "kg",
    kgCo2ePerActivityUnit: 1.40277,
    boundary: "material-production-only",
    gwpBasis: "Legacy source metadata; human re-review required",
    quality: "proxy",
    reviewStatus: "estimate_only",
    buyerReadyEligible: false,
    validFrom: "2025-01-01",
    validTo: "2025-12-31",
    source: {
      publisher: "UK DESNZ / DEFRA",
      title: "Government GHG Conversion Factors for Company Reporting 2025 - Material use",
      version: "2025",
      referenceYear: 2025,
      reviewedAt: "2026-08-17",
      nextReviewAt: "2026-06-30",
      sourceUrl: "https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2025",
      licence: "Open Government Licence v3.0 - exact row/boundary must be rechecked",
      sourceType: "official",
      notes: "Mevcut repo örnek raporundan migrate edilmiştir; 2026 veri setiyle yenilenmeden seçilemez.",
    },
    limitations: [
      "Türkiye üretim koşullarını temsil etmeyebilir.",
      "2026 DESNZ veri seti yayımlandığı için tazelik kapısından geçmez.",
    ],
  },
  {
    id: "legacy-defra-2025-pvc-generic",
    kind: "material",
    labelTr: "PVC - eski genel kayıt",
    labelEn: "PVC - legacy generic record",
    materialIds: ["pvc"],
    aliases: ["pvc", "polivinil klorür"],
    geographies: ["GLOBAL_PROXY"],
    activityUnit: "kg",
    kgCo2ePerActivityUnit: 2.94476,
    boundary: "material-production-only",
    gwpBasis: "Legacy source metadata; human re-review required",
    quality: "proxy",
    reviewStatus: "estimate_only",
    buyerReadyEligible: false,
    validFrom: "2025-01-01",
    validTo: "2025-12-31",
    source: {
      publisher: "UK DESNZ / DEFRA",
      title: "Government GHG Conversion Factors for Company Reporting 2025 - Material use",
      version: "2025",
      referenceYear: 2025,
      reviewedAt: "2026-08-17",
      nextReviewAt: "2026-06-30",
      sourceUrl: "https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2025",
      licence: "Open Government Licence v3.0 - exact row/boundary must be rechecked",
      sourceType: "official",
      notes: "Mevcut repo örnek raporundan migrate edilmiştir; 2026 veri setiyle yenilenmeden seçilemez.",
    },
    limitations: [
      "Türkiye üretim koşullarını temsil etmeyebilir.",
      "2026 DESNZ veri seti yayımlandığı için tazelik kapısından geçmez.",
    ],
  },
];

export const PCF_FACTORS = validateFactorRegistry(RAW_FACTORS);
