import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Building2, CheckCircle2, Link2, Network, Ship, Users } from "lucide-react";
import { pageMetadata } from "@/lib/skdm/seo";

export const metadata: Metadata = pageMetadata({ path: "/denizcilik/cbam-ihracatci-masasi/", title: "CBAM İhracatçı Masası — Denizcilik Partner Kanalı", description: "Denizcilik ve lojistik firmalarının ihracatçı müşteri portföyünü SKDMHesapla CBAM kapsam kontrolü ve hizmet talebi kanalına dönüştüren partner modeli." });

const steps = [
  ["1", "Partner bağlantısı", "Denizcilik firmasına ölçülebilir bir partner kimliği ve yönlendirme bağlantısı tanımlanır."],
  ["2", "İhracatçı giriş yapar", "Müşteri kendi GTİP/CN bilgisiyle SKDM kapsam kontrolüne girer; denizcilik firması veri girmek zorunda kalmaz."],
  ["3", "Nitelikli CBAM talebi oluşur", "Kapsam içi veya veri hazırlığı gereken ihracatçılar SKDMHesapla satış akışına geçer."],
  ["4", "Partner görünürlüğü", "Kaynak firma, yönlendirme, nitelikli talep ve dönüşüm verisi ayrı izlenir; ticari model sözleşmeyle belirlenir."],
] as const;

export default function CbamIhracatciMasasiPage() {
  return (
    <main className="min-h-screen bg-white text-ink-900">
      <section className="border-b border-line bg-[#071812] py-16 text-white sm:py-24"><div className="mx-auto max-w-6xl px-5 sm:px-6"><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/[0.06] px-4 py-2 text-xs font-black uppercase tracking-[0.12em] text-brand-300"><Network className="h-4 w-4" /> B2B2B dağıtım modeli</span><h1 className="mt-5 max-w-5xl text-4xl font-black tracking-tight sm:text-6xl">Denizcilik firmasını tek müşteriden, sürekli CBAM müşteri kanalı haline getirin</h1><p className="mt-6 max-w-3xl text-base font-medium leading-8 text-slate-300 sm:text-lg">Firma önce kendi EU ETS / MRV / FuelEU uyumunu yönetir. Sonra aynı dijital ilişkiyi AB'ye ihracat yapan müşteri portföyüne açar. İhracatçı GTİP kontrolüne girer; uygun olan CBAM müşterisine dönüşür.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/iletisim/" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-brand-500 px-6 text-sm font-black text-brand-950 hover:bg-brand-400">Partner görüşmesi başlat <ArrowRight className="h-4 w-4" /></Link><Link href="/denizcilik/" className="inline-flex min-h-12 items-center rounded-xl border border-white/20 px-6 text-sm font-black text-white hover:bg-white/[0.06]">Denizcilik ana sayfası</Link></div></div></section>
      <section className="py-14 sm:py-20"><div className="mx-auto max-w-6xl px-5 sm:px-6"><div className="grid gap-4 lg:grid-cols-4">{steps.map(([no, title, text]) => <article key={no} className="rounded-3xl border border-line bg-[#fbfdfb] p-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-100 font-black text-brand-950">{no}</span><h2 className="mt-4 text-lg font-black">{title}</h2><p className="mt-2 text-sm font-medium leading-7 text-ink-700">{text}</p></article>)}</div></div></section>
      <section className="border-y border-line bg-[#f7faf8] py-14 sm:py-20"><div className="mx-auto grid max-w-6xl gap-6 px-5 sm:px-6 lg:grid-cols-[1fr_1fr]"><article className="rounded-3xl border border-line bg-white p-6 sm:p-8"><div className="flex items-center gap-3"><Ship className="h-6 w-6 text-brand-800" /><h2 className="text-2xl font-black">Denizcilik firmasına satılan değer</h2></div><ul className="mt-5 space-y-3">{["EU MRV kapsam ve veri hazırlığı", "EU ETS maliyet maruziyeti", "FuelEU veri ve verifier hazırlığı", "Yıllık filo/kanıt iş akışı"].map((item) => <li key={item} className="flex gap-2 text-sm font-medium leading-6 text-ink-700"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-brand-700" /> {item}</li>)}</ul></article><article className="rounded-3xl border border-brand-800/20 bg-brand-50 p-6 sm:p-8"><div className="flex items-center gap-3"><Users className="h-6 w-6 text-brand-900" /><h2 className="text-2xl font-black">SKDMHesapla'ya kazandırılan değer</h2></div><ul className="mt-5 space-y-3">{["Hazır ihracatçı müşteri portföyüne erişim", "GTİP tabanlı nitelikli lead üretimi", "Partner bazlı kaynak ve dönüşüm ölçümü", "Tek seferlik reklam yerine sürekli B2B2B dağıtım"].map((item) => <li key={item} className="flex gap-2 text-sm font-medium leading-6 text-ink-700"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-brand-700" /> {item}</li>)}</ul></article></div></section>
      <section className="py-14 sm:py-20"><div className="mx-auto max-w-5xl px-5 sm:px-6"><span className="text-xs font-black uppercase tracking-[0.12em] text-brand-800">Örnek kullanıcı akışı</span><div className="mt-5 rounded-3xl border border-line bg-white p-5 shadow-xl shadow-black/[0.04] sm:p-8"><div className="grid gap-3 md:grid-cols-5 md:items-stretch">{[[Building2, "ABC Shipping", "Partner"], [Link2, "Özel link", "Kaynak kimliği"], [Users, "İhracatçı", "GTİP kontrolü"], [CheckCircle2, "Nitelikli talep", "CBAM ihtiyacı"], [Network, "SKDMHesapla", "Satış / hizmet"]].map(([Icon, title, text], index) => { const Cmp = Icon as typeof Building2; return <div key={title as string} className="relative rounded-2xl border border-line bg-[#fbfdfb] p-4 text-center"><Cmp className="mx-auto h-5 w-5 text-brand-800" /><p className="mt-2 text-sm font-black">{title as string}</p><p className="mt-1 text-xs font-medium text-ink-600">{text as string}</p>{index < 4 && <span className="absolute -right-2 top-1/2 hidden -translate-y-1/2 font-black text-brand-700 md:block">→</span>}</div>; })}</div></div></div></section>
      <section className="border-t border-line bg-brand-950 py-14 text-white"><div className="mx-auto max-w-4xl px-5 text-center sm:px-6"><h2 className="text-3xl font-black">Partner modeli teknoloji kadar satış kuralı gerektirir.</h2><p className="mx-auto mt-3 max-w-2xl text-sm font-medium leading-7 text-slate-300">Attribution, müşteri sahipliği, veri erişimi, komisyon/indirim ve KVKK rolleri sözleşmede belirlenmeden otomatik paylaşım veya gelir vaadi yapılmamalıdır.</p><Link href="/iletisim/" className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-xl bg-brand-500 px-6 text-sm font-black text-brand-950 hover:bg-brand-400">Kurumsal partner görüşmesi <ArrowRight className="h-4 w-4" /></Link></div></section>
    </main>
  );
}
