// SKDM Sözlüğü — veri kaynağı (Plan 29)
import { SITE } from "../site-config";
import { legalFactRender } from "@/lib/seo/legal-facts";

export interface SozlukTerim {
  id: string;
  en: string; // İngilizce karşılık (yoksa "")
  tr: string; // Türkçe karşılık / başlık
  tanim: string;
  nerede: string; // Kullanım yeri
  kategori: string; // SOZLUK_KATEGORILERI id'si
}

export const SOZLUK_KATEGORILERI = [
  { id: "temel", ad: "Temel Kavramlar" },
  { id: "taraflar", ad: "Taraflar ve Roller" },
  { id: "emisyon", ad: "Emisyon ve Hesaplama Terimleri" },
  { id: "sablon", ad: "Resmi Şablon ve Veri Alanları" },
  { id: "sertifika", ad: "Sertifika, Fiyat ve Maliyet" },
  { id: "dogrulama", ad: "Doğrulama ve Denetim" },
  { id: "gumruk", ad: "Gümrük ve Ticaret Kodları" },
  { id: "celik", ad: "Üretim ve Malzeme Terimleri" },
  { id: "mevzuat", ad: "Mevzuat ve Kurumlar" },
  { id: "turkiye", ad: "Türkiye Tarafı (TR-ETS ve Kurumlar)" },
  { id: "yesil", ad: "İlişkili AB Yeşil Mutabakat Düzenlemeleri" },
] as const;

export const SOZLUK_TERIMLERI: SozlukTerim[] = [
  // ── TEMEL ──
  { id: "cbam", en: "CBAM (Carbon Border Adjustment Mechanism)", tr: "Sınırda Karbon Düzenleme Mekanizması (SKDM)", kategori: "temel",
    tanim: "AB'ye ithal edilen belirli ürünlerin üretiminde oluşan karbon emisyonunu, AB içindeki üreticinin ödediği karbon fiyatıyla eşitleyen düzenleme. Amaç, üretimin iklim kuralları zayıf ülkelere kaymasını (karbon kaçağını) önlemek.",
    nerede: "AB resmi metinlerinde 'CBAM', Türkçe kullanımda 'SKDM'. Alıcınızın yazışmalarında, gümrük ve ticaret sözleşmelerinde." },
  { id: "embedded-emissions", en: "Embedded emissions", tr: "Gömülü emisyonlar", kategori: "temel",
    tanim: "Bir ürünün üretimi sırasında doğrudan ve dolaylı olarak atmosfere salınan sera gazlarının, ürünün bir tonu başına ton CO₂ eşdeğeri cinsinden karşılığı. SKDM'nin fiyatladığı tek şey budur.",
    nerede: "Alıcınızın sizden istediği nihai sayı. İletişim şablonunun ana çıktı alanı." },
  { id: "carbon-leakage", en: "Carbon leakage", tr: "Karbon kaçağı", kategori: "temel",
    tanim: "AB firmalarının karbon maliyetinden kaçınmak için üretimi karbon fiyatı olmayan ülkelere kaydırması riski. SKDM bu kaçışı engellemek için yürürlüğe konmuştur.",
    nerede: "Mevzuat gerekçelerinde ve politika metinlerinde; günlük operasyonda karşınıza çıkmaz." },
  { id: "vergi-degil", en: "CBAM is not a tax", tr: "SKDM bir vergi değildir", kategori: "temel",
    tanim: "SKDM gümrük vergisi veya karbon vergisi değildir; ithalatçının satın aldığı emisyon sertifikalarına dayanan bir fiyatlandırma mekanizmasıdır. Sertifikalar şirketler arasında alınıp satılamaz.",
    nerede: "Alıcınızla ve resmi yazışmalarda 'karbon vergisi' demeyin; doğru ifade 'SKDM sertifika maliyeti'." },
  { id: "transitional", en: "Transitional period", tr: "Geçiş dönemi", kategori: "temel",
    tanim: "1 Ekim 2023 – 31 Aralık 2025 arası yalnızca raporlama yapılan, mali yükümlülüğün olmadığı dönem. Son geçiş dönemi raporu 31 Ocak 2026'da verildi; bu dönem kapanmıştır.",
    nerede: "Eski yazışma ve raporlarda. Artık yalnızca tarihsel referans." },
  { id: "definitive", en: "Definitive regime", tr: "Kesin dönem", kategori: "temel",
    tanim: "1 Ocak 2026'dan itibaren geçerli dönem: ithalat mali yükümlülük doğurur, yıllık beyan ve sertifika teslimi gerekir. İlk yıllık beyan 30 Eylül 2027'de, 2026 ithalatını kapsar.",
    nerede: "Tüm güncel yükümlülük metinleri. 'Definitive period' ile aynı anlam." },
  { id: "mrv", en: "MRV (Monitoring, Reporting, Verification)", tr: "İzleme, Raporlama, Doğrulama", kategori: "temel",
    tanim: "Emisyon verisinin nasıl toplanacağını (izleme), nasıl beyan edileceğini (raporlama) ve kimin teyit edeceğini (doğrulama) belirleyen üç ayaklı güven sistemi. SKDM'nin tüm veri mimarisi bu çerçeveye oturur.",
    nerede: "AB ETS ve SKDM teknik dokümanları; sizin izleme planınızın dayanağı." },
  { id: "de-minimis", en: "De minimis threshold", tr: "50 ton muafiyet eşiği", kategori: "temel",
    tanim: "Bir ithalatçının bir takvim yılındaki toplam SKDM ürünü ithalatı 50 tonu geçmezse o yıl için yükümlülük doğmaz. Çimento, demir-çelik, alüminyum ve gübre için geçerli; elektrik ve hidrojende uygulanmaz. Eşik ithalatçı bazındadır — sizin ihracatınızı değil, alıcınızın toplam ithalatını ilgilendirir.",
    nerede: "Omnibus (AB) 2025/2083. Küçük alıcılarınızın 'bana bir şey gerekmez' demesinin yasal dayanağı." },
  { id: "omnibus", en: "Omnibus Simplification Package", tr: "Omnibus Sadeleştirme Paketi", kategori: "mevzuat",
    tanim: "Ekim 2025'te kabul edilen (AB) 2025/2083 sayılı paket: 50 ton eşiği, sertifika satışının Şubat 2027'ye ertelenmesi, çeyreklik bulundurma oranının %80'den %50'ye indirilmesi ve küçük aşımlarda ceza indirimi gibi sadeleştirmeleri getirdi.",
    nerede: "2026 sonrası tüm pratik kuralların kaynağı; rehberin takvim bölümü." },
  // ── TARAFLAR ──
  { id: "declarant", en: "Authorised CBAM declarant", tr: "Yetkili SKDM beyan sahibi", kategori: "taraflar",
    tanim: "SKDM ürünü ithal eden ve yıllık beyanı verip sertifikaları teslim etmekle yükümlü AB tarafı. 50 ton üzeri ithalat yapan herkes bu statüye başvurmak zorunda; 31 Mart 2026'ya kadar başvuranlar, başvuru incelenirken ithalata devam edebildi. Bu kişi siz değilsiniz — AB'li alıcınızdır.",
    nerede: "AB SKDM Kayıt Sistemi (Registry). Alıcınızın size veri istemesinin sebebi bu statü." },
  { id: "operator", en: "Operator", tr: "İşletmeci (tesis işleteni)", kategori: "taraflar",
    tanim: "Üçüncü ülkedeki üretim tesisini işleten kişi — yani sizsiniz. Gömülü emisyon verisini üretmek, izleme planına göre kayıt tutmak ve isterseniz doğrulatmak sizin sorumluluğunuzdadır.",
    nerede: "İletişim şablonunun 'installation/operator' alanları; SKDMHesapla sihirbazının 1. adımı." },
  { id: "installation", en: "Installation", tr: "Tesis", kategori: "taraflar",
    tanim: "SKDM ürününün fiziksel olarak üretildiği fabrika veya saha. Şirketinizin birden fazla tesisi varsa her biri ayrı beyan edilir; emisyonlar tesis bazında hesaplanır.",
    nerede: "Şablonun A bölümü (tesis adı, adres, UNLOCODE, koordinat). Sihirbaz 1. adım." },
  { id: "accredited-verifier", en: "Accredited verifier", tr: "Akredite doğrulayıcı", kategori: "taraflar",
    tanim: "Gerçek emisyon verinizi yerinde inceleyip doğrulama raporu düzenleyen, AB üye devletlerinde akredite bağımsız kuruluş. Gerçek veri kullanacaksanız doğrulama raporu zorunludur; doğrulanmamış gerçek veri beyanda kullanılamaz.",
    nerede: "Delegated Regulation (AB) 2025/2551. Sihirbazın 7. adımı (doğrulayıcı bilgisi)." },
  { id: "registry", en: "CBAM Registry", tr: "SKBM Kayıt Sistemi", kategori: "taraflar",
    tanim: "Beyan sahiplerinin hesap açtığı, beyanları verdiği ve sertifikaların tutulduğu AB'nin merkezi dijital sistemi. Üçüncü ülke işletmecileri için tesis ve emisyon verilerini paylaşabilecekleri ayrı bir 'operators' bölümü vardır — verinizi buraya bir kez girerek birden çok alıcıyla paylaşabilirsiniz.",
    nerede: "AB Komisyonu SKDM portalı. Alıcınız 'Registry'ye yükleyin' derse bu bölümü kastediyor." },
  { id: "customs-rep", en: "Indirect customs representative", tr: "Dolaylı gümrük temsilcisi", kategori: "taraflar",
    tanim: "İthalatçı adına gümrük işlemlerini yürüten ve koşullara bağlı olarak SKDM beyan yükümlülüğünü de üstlenebilen temsilci. Alıcınız küçükse yükümlülük onun temsilcisine geçmiş olabilir.",
    nerede: "Tüzük Md. 5; lojistik/gümrük sözleşmelerinizde." },
  { id: "competent-authority", en: "Competent authority", tr: "Yetkili otorite", kategori: "taraflar",
    tanim: "Her AB üye devletinde SKDM'nin uygulanmasından sorumlu ulusal kurum (örn. Almanya'da DEHSt). Beyan sahibi başvuruları, cezalar ve geri alım işlemleri bu otoriteler üzerinden yürür.",
    nerede: "Alıcınızın resmi yazışmalarında; ceza ve geri alım süreçlerinde." },
  // ── EMİSYON ──
  { id: "direct-emissions", en: "Direct emissions", tr: "Doğrudan emisyonlar", kategori: "emisyon",
    tanim: "Tesisinizde yakıt yakılması ve kimyasal süreçlerden doğan emisyonlar (doğalgaz, kok, kireç taşı kalsinasyonu vb.). Tüm sektörlerde fiyatlandırılır.",
    nerede: "Sihirbaz 4. adım (enerji/yakıt) ve süreç emisyonu kayıtları." },
  { id: "indirect-emissions", en: "Indirect emissions", tr: "Dolaylı emisyonlar", kategori: "emisyon",
    tanim: "Üretimde kullanılan elektriğin üretimi sırasında oluşan emisyonlar. Kritik kural: yalnızca çimento ve gübrede fiyatlandırılır; demir-çelik, alüminyum, elektrik ve hidrojende Ek II gereği maliyete girmez (yine de raporlanır).",
    nerede: "Ek II (Annex II). Alüminyum ve çelik ihracatçısı için 'elektrik faturam maliyeti patlatır' korkusunun yersiz olduğunun dayanağı." },
  { id: "annex-ii", en: "Annex II", tr: "Ek II — yalnızca doğrudan emisyon listesi", kategori: "emisyon",
    tanim: "Tüzüğün, hangi ürünlerde yalnızca doğrudan emisyonların fiyatlandırılacağını gösteren eki. Demir-çelik, alüminyum, elektrik ve hidrojen bu listede; çimento ve gübrede hem doğrudan hem dolaylı emisyon fiyatlanır. Kontrol CN kodu bazında yapılır — sektör genelinde genelleme yapılmaz.",
    nerede: "Maliyet hesabınızın birinci belirleyicisi. Sihirbaz bunu kod bazında otomatik uygular." },
  { id: "actual-values", en: "Actual values", tr: "Gerçek (ölçülmüş) değerler", kategori: "emisyon",
    tanim: "Tesisinizin izleme planına göre ölçüp akredite doğrulayıcıya teyit ettirdiği emisyon verisi. Varsayılan değerler genellikle cezalı olduğundan gerçek veri çoğu zaman avantajlıdır — ama kural değildir; yüksek emisyonlu tesislerde tersi olabilir.",
    nerede: "Beyan tercihi. Sihirbazın register adımları gerçek veri yolunu açar." },
  { id: "default-values", en: "Default values", tr: "Varsayılan değerler", kategori: "emisyon",
    tanim: "Gerçek veri yoksa kullanılan, ülke ve ürün bazında Komisyonun belirlediği ortalama emisyon değerleri. Kesin dönemde üzerine mark-up eklenir: 2026'da +%10, 2027'de +%20, 2028'den itibaren +%30 (gübrede sabit +%1). Geçiş dönemi varsayılanlarından farklı ve genelde daha yüksektir.",
    nerede: "IR (AB) 2025/2621. Veri vermezseniz alıcınızın maruz kalacağı maliyetin dayanağı." },
  { id: "markup", en: "Default value mark-up", tr: "Varsayılan değer artırımı (mark-up)", kategori: "emisyon",
    tanim: "Varsayılan değerleri cezalandırıp gerçek veriyi teşvik eden katsayı: çelik, çimento, alüminyum ve hidrojende 2026 +%10, 2027 +%20, 2028+ +%30; gübrede tarım fiyatlarına duyarlılık nedeniyle sabit +%1.",
    nerede: "IR (AB) 2025/2621. 'Veri vermezsem ne olur?' sorusunun parasal cevabı." },
  { id: "see", en: "SEE (Specific Embedded Emissions)", tr: "Özgül gömülü emisyon", kategori: "emisyon",
    tanim: "Bir ürünün bir tonu başına düşen gömülü emisyon (tCO₂e/t). Alıcınızın sizden istediği tek nihai sayı budur; tüm izleme ve hesaplama bu sayıyı üretmek içindir.",
    nerede: "İletişim şablonunun E ve Summary bölümleri; sözleşme ve teklif ekleri." },
  { id: "emission-factor", en: "Emission factor", tr: "Emisyon faktörü", kategori: "emisyon",
    tanim: "Bir birim faaliyet verisinin (örn. 1 ton doğalgaz) kaç ton CO₂e ürettiğini gösteren katsayı. Yakıt ve hammaddenize göre mevzuat eklerinden veya ölçümle belirlenir.",
    nerede: "Hesaplama eki; sihirbaz 4. adımdaki kaynak akışı kayıtları." },
  { id: "activity-data", en: "Activity data", tr: "Faaliyet verisi", kategori: "emisyon",
    tanim: "Dönem içinde tüketilen yakıt, hammadde veya üretilen ürün miktarı gibi ölçülen ham sayı (fatura, sayaç, tartım kaydı). Emisyon = faaliyet verisi × emisyon faktörü.",
    nerede: "Şablonun B_EmInst sayfasındaki AD sütunu; sihirbaz 4. adım." },
  { id: "ncv", en: "NCV (Net Calorific Value)", tr: "Net kalorifik değer", kategori: "emisyon",
    tanim: "Yakıtın birim kütlesindeki kullanılabilir enerji miktarı. Yakıt bazlı hesaplamada faaliyet verisini enerjiye çevirmek için kullanılır; faturada veya laboratuvar analizinde bulunur.",
    nerede: "Şablonun B_EmInst NCV sütunu; doğalgaz ve katı yakıt kullanan tesislerde." },
  { id: "source-stream", en: "Source stream", tr: "Kaynak akışı", kategori: "emisyon",
    tanim: "Tesise giren veya çıkan, emisyon doğuran her tekil akım: bir yakıt türü, bir hammadde, bir süreç çıkışı. İzleme planında her akış ayrı satır olarak tanımlanır.",
    nerede: "Şablonun B sayfası; sihirbazın 'Enerji ve yakıt' adımındaki kayıtlar." },
  { id: "combustion-process", en: "Combustion / Process emissions", tr: "Yanma / süreç emisyonları", kategori: "emisyon",
    tanim: "Yanma emisyonu yakıttan (doğalgaz, kok), süreç emisyonu kimyasal reaksiyondan doğar (kireç taşının kalsinasyonu, elektrot tüketimi gibi). Hesap yöntemi ikisinde farklıdır; şablonda ayrı işaretlenir.",
    nerede: "B_EmInst 'method' alanı: Combustion / Process / Mass balance seçimi." },
  { id: "mass-balance", en: "Mass balance", tr: "Kütle dengesi yöntemi", kategori: "emisyon",
    tanim: "Özellikle çelikte kullanılan hesap yöntemi: tesise giren karbonlu malzemeler ile çıkanlar arasındaki fark üzerinden emisyon bulunur. BF-BOF tesislerinde standart yaklaşımdır.",
    nerede: "B_EmInst method seçeneklerinden biri; entegre çelik tesisleri." },
  { id: "functional-unit", en: "Functional unit", tr: "Fonksiyonel birim", kategori: "emisyon",
    tanim: "Emisyonun bölündüğü referans miktar — SKDM'de bu 'bir ton ürün'dür. SEE hesabının paydası.",
    nerede: "Hesaplama eki ve Summary sayfası." },
  { id: "simple-goods", en: "Simple goods", tr: "Basit ürünler", kategori: "emisyon",
    tanim: "Üretimi yalnızca kendi tesisinizdeki girdilerle yapılan, kapsam içi öncül madde içermeyen ürünler. Hesabı kısadır: yalnızca kendi emisyonlarınız.",
    nerede: "Şablon tanımları; sihirbaz ürün kaydında rota seçimi." },
  { id: "complex-goods", en: "Complex goods", tr: "Karmaşık ürünler", kategori: "emisyon",
    tanim: "Üretiminde SKDM kapsamında öncül madde (precursor) kullanılan ürünler. Kendi emisyonunuza ek olarak öncül maddenin gömülü emisyonunu da hesaba katmanız gerekir.",
    nerede: "Şablon E_PurchPrec sayfası; sihirbaz 6. adım (hammaddeler)." },
  { id: "precursor", en: "Precursor", tr: "Öncül madde", kategori: "emisyon",
    tanim: "Ürettiğiniz ürüne giren ve kendisi de SKDM kapsamında olan ara girdi (çelik için DRI/HBI, ferro-alaşımlar gibi). Tedarikçinizden SEE değerini istemeniz gerekir; alamazsanız varsayılan değer uygulanır. Hurda (CN 7204) öncül sayılmaz.",
    nerede: "Sihirbaz 6. adım; tedarikçi yazışmalarınız." },
  { id: "bubble-approach", en: "Bubble approach", tr: "Balon yaklaşımı", kategori: "emisyon",
    tanim: "Aynı ürün grubunu üreten birden fazla üretim hattının tek bir 'balon' içinde toplu izlenmesine izin veren yöntem; her hat için ayrı ölçüm zorunluluğunu kaldırır. Sihirbazdaki P1–P10 süreç kayıtları bu mantıkla çalışır.",
    nerede: "IR 2025/2547 izleme kuralları; şablonun A.4(b) alanı." },
  { id: "benchmark", en: "Benchmark", tr: "Kıyas değeri (benchmark)", kategori: "emisyon",
    tanim: "AB ETS'te bedelsiz tahsisi belirleyen, ürün bazlı emisyon referans değeri. SKDM maliyeti, gömülü emisyonun bu kıyas değerini aşan kısmı üzerinden hesaplanır — bedelsiz tahsis azaldıkça sizin payınıza düşen maliyet artar.",
    nerede: "Maliyet formülü; 'CBAM faktörü' ile birlikte." },
  { id: "heat-waste-gas", en: "Waste heat / waste gases", tr: "Atık ısı / atık gazlar", kategori: "emisyon",
    tanim: "Üretimde açığa çıkan ve yeniden kullanılan ısı veya proses gazları (örn. kok fırını gazı). İthal/ihraç edilen ısı ve gaz akışları şablonda ayrıca raporlanır; doğru kaydedilmezse emisyon fazla hesaplanır.",
    nerede: "B_EmInst ek satırları; entegre çelik ve kimya tesisleri." },
  // ── ŞABLON ──
  { id: "communication-template", en: "CBAM Communication Template", tr: "SKDM iletişim şablonu", kategori: "sablon",
    tanim: "Komisyonun yayımladığı, işletmecinin emisyon verisini ithalatçıya ilettiği resmi Excel çalışma kitabı. Çıktı formatıdır, veri modeli değildir — asıl veri yapısı IR 2025/2547'nin izleme planı ve emisyon raporu tanımlarıdır.",
    nerede: "Alıcınız büyük olasılıkla size bu dosyayı gönderdi. Paketinizdeki 4. dosya bu formatta üretilir." },
  { id: "monitoring-plan", en: "Monitoring plan", tr: "İzleme planı", kategori: "sablon",
    tanim: "Tesisinizin hangi kaynak akışlarını, hangi yöntemle, hangi ölçüm cihazlarıyla izleyeceğini tanımlayan belge. Gerçek veri kullanmanın ön şartı; doğrulayıcının ilk incelediği doküman.",
    nerede: "IR 2025/2547. Paketinizdeki 1. dosya." },
  { id: "emissions-report", en: "Operator's emissions report", tr: "İşletmeci emisyon raporu", kategori: "sablon",
    tanim: "İzleme planına göre toplanan verilerle dönem sonunda üretilen, tesisin ve ürünlerin gömülü emisyonlarını içeren rapor. Doğrulayıcı bu raporu inceler.",
    nerede: "IR 2025/2547. Paketinizdeki 2. dosya." },
  { id: "summary", en: "Summary communication", tr: "Özet iletişim (Summary)", kategori: "sablon",
    tanim: "Şablonun, ürün bazında nihai SEE değerlerini özetleyen sayfası. Alıcınızın esas baktığı yer burasıdır.",
    nerede: "İletişim şablonunun son sayfası; alıcı paketinizin özü." },
  { id: "unlocode", en: "UN/LOCODE", tr: "BM konum kodu", kategori: "gumruk",
    tanim: "Birleşmiş Milletler'in yerleşim ve lojistik noktalarına verdiği 5 harfli kod (İstanbul TRIST, İzmir TRIZM gibi). Şablonun tesis kimlik alanında istenir; lojistik belgelerinizde veya gümrük müşavirinizde bulunur.",
    nerede: "Şablon A bölümü; sihirbaz 1. adım." },
  { id: "kontrol-denkligi", en: "Control equality (a = b + c + d)", tr: "Kontrol denkliği", kategori: "sablon",
    tanim: "Üretim miktarı beyanlarında toplam üretimin (a), pazara giden (b) + tesis içi kullanım (c) + diğer/stok (d) toplamına eşit olması zorunluluğu. Tutmazsa doğrulayıcı 'material misstatement' şüphesiyle döner.",
    nerede: "Şablon D_Processes sayfası; sihirbaz 5. adımdaki canlı kontrol." },
  { id: "record-keeping", en: "Record keeping", tr: "Kayıt saklama", kategori: "dogrulama",
    tanim: "Beyana dayanak tüm belgelerin (fatura, sayaç, analiz, kalibrasyon) beyan yılını izleyen 4 yıl boyunca saklanması zorunluluğu. Türkiye pratiği için 5 yıl saklamanızı öneririz.",
    nerede: "Tüzük ve IR; paketinizdeki Kanıt Kayıt Defteri bu amaçla tasarlandı." },
];

// ── devam: sertifika, doğrulama, gümrük, çelik, mevzuat, Türkiye, yeşil mutabakat ──
export const SOZLUK_TERIMLERI_2: SozlukTerim[] = [
  // ── SERTİFİKA ──
  { id: "certificate", en: "CBAM certificate", tr: "SKDM sertifikası", kategori: "sertifika",
    tanim: "Bir ton CO₂e gömülü emisyonu karşılayan dijital belge. Yalnızca AB'nin merkezi platformundan alınır, şirketler arasında alınıp satılamaz, ikincil piyasası yoktur. Siz değil, AB'li alıcınız satın alır.",
    nerede: "Tüzük Md. 20-23. 'Sertifikayı kim ödüyor?' sorusunun cevabı." },
  { id: "certificate-price", en: "CBAM certificate price", tr: "Sertifika fiyatı", kategori: "sertifika",
    tanim: "AB ETS ihale fiyatlarına bağlanır: 2026 ithalatı için çeyreklik ortalama, 2027'den itibaren haftalık ortalama. Yayımlanan ilk fiyatlar: 2026 Q1 = 75,36 €/tCO₂e, Q2 = 75,28 €/tCO₂e. Satın alınan sertifikanın fiyatı sabitlenir; sonraki fiyat hareketleri geriye dönük etkilemez.",
    nerede: "Komisyonun sertifika fiyat sayfası ve Registry. Maliyet projeksiyonunuzun çarpanı." },
  { id: "quarterly-average", en: "Quarterly ETS average", tr: "Çeyreklik ETS ortalaması", kategori: "sertifika",
    tanim: "2026 yılı ithalatına uygulanan fiyat hesabı: her çeyreğin ETS ihale kapanış fiyatlarının ağırlıklı ortalaması, çeyrek bitiminden sonraki ilk hafta yayımlanır. Q3 2026 için 5 Ekim 2026, Q4 için 4 Ocak 2027.",
    nerede: "2026 maliyet hesabınızın resmi fiyat kaynağı." },
  { id: "surrender", en: "Surrender of certificates", tr: "Sertifika teslimi", kategori: "sertifika",
    tanim: "Beyan sahibinin yıllık beyanıyla birlikte, beyan edilen gömülü emisyonu karşılayan sayıda sertifikayı sisteme iade etmesi. İlk teslim: 30 Eylül 2027 (2026 ithalatı için).",
    nerede: "Yıllık uyum takviminin son halkası." },
  { id: "holding", en: "Quarterly holding requirement", tr: "Çeyreklik bulundurma zorunluluğu (%50)", kategori: "sertifika",
    tanim: "2027'den itibaren beyan sahibi, her çeyrek sonunda yıl başından o güne kadarki ithalatının gömülü emisyonunun en az %50'si kadar sertifikayı hesabında bulundurmak zorunda. Aşım her çeyrekte ayrı denetlenir; eksiklik ton başına 100 € ceza doğurur.",
    nerede: "Omnibus sonrası Md. 22. Alıcınızın nakit planlaması — sizin veri zamanlamanızı etkiler." },
  { id: "repurchase", en: "Repurchase (buyback)", tr: "Geri alım", kategori: "sertifika",
    tanim: "Teslim sonrası elde kalan fazla sertifikaların, yetkili otoriteye alış fiyatından geri satılabilmesi (beyan edilen emisyonun belli bir oranıyla sınırlı). Tek geri dönüş yoludur; başka firmaya satış yasaktır.",
    nerede: "Tüzük Md. 23. Alıcınızın 'fazla alırsam?' sorusunun cevabı." },
  { id: "penalty", en: "Penalty", tr: "Ceza (ton başına 100 €)", kategori: "sertifika",
    tanim: "Teslim edilmeyen her ton CO₂e için 100 € idari ceza + eksik sertifikanın yine de tamamlanması. Yanlış veya hileli beyanda yetkili statüsünün iptali ve üye devlet hukukuna göre ek yaptırımlar gündeme gelir. Eşiği %10'a kadar küçük aşımlarda ve doğrulanmış üçüncü taraf hatalarında indirim mümkün.",
    nerede: "Tüzük Md. 26. Alıcınızın sizden doğru veri istemesinin asıl motivasyonu." },
  { id: "free-allocation", en: "Free allocation", tr: "Bedelsiz tahsis", kategori: "sertifika",
    tanim: "AB içi üreticiye ETS'te bedava verilen emisyon hakkı. 2026-2034 arasında kademeli kaldırılır; SKDM yükümlülüğü de aynı oranda (CBAM faktörü) artar. İki mekanizma aynanın iki yüzüdür.",
    nerede: "Maliyet projeksiyonunuzun yıllar içinde neden arttığının açıklaması." },
  { id: "cbam-factor", en: "CBAM factor", tr: "SKDM faktörü", kategori: "sertifika",
    tanim: "Bedelsiz tahsisin kaldırılma oranını yansıtan katsayı: 2026'da %2,5'ten başlar, 2034'te %100'e ulaşır. Yükümlülük = gömülü emisyon × faktör × sertifika fiyatı − mahsuplar.",
    nerede: "Maliyet formülü; uzun vadeli fiyat görüşmelerinizin çekirdeği." },
  { id: "carbon-price-paid", en: "Carbon price paid in a third country", tr: "Üçüncü ülkede ödenen karbon fiyatı (mahsup)", kategori: "sertifika",
    tanim: "Ürünün üretildiği ülkede zorunlu bir karbon fiyatı ödendiyse, kanıtlanmak koşuluyla sertifika yükümlülüğünden düşülür. Türkiye'de pilot TR-ETS %100 bedelsiz tahsisli olduğundan ödenen fiili fiyat sıfırdır — mahsup alanı 0 girilir ve sistemde sabit açıklaması gösterilir.",
    nerede: "Tüzük Md. 9; sihirbazın 8. adımı (karbon bedeli)." },
  // ── DOĞRULAMA ──
  { id: "verification-report", en: "Verification report", tr: "Doğrulama raporu", kategori: "dogrulama",
    tanim: "Akredite doğrulayıcının, emisyon raporunuzu inceledikten sonra düzenlediği resmi belge. Gerçek verinizin beyanda kullanılabilmesinin tek kanıtı; rapor olmadan gerçek veri 'yok' sayılır.",
    nerede: "Delegated Regulation (AB) 2025/2551; doğrulayıcı sözleşmenizin çıktısı." },
  { id: "site-visit", en: "Site visit", tr: "Saha ziyareti", kategori: "dogrulama",
    tanim: "Doğrulayıcının tesisinizi yerinde incelemesi. İlk doğrulamada ve izleme yöntemi değişikliklerinde esasen zorunlu; bu yüzden şablondaki tesis adresinin kesin doğru olması gerekir.",
    nerede: "Doğrulama planlaması; sihirbaz 1. adımdaki adres alanının önemi." },
  { id: "misstatement", en: "Material misstatement", tr: "Esaslı yanlışlık", kategori: "dogrulama",
    tanim: "Doğrulayıcının, beyan edilen emisyonda kararı etkileyecek büyüklükte bir sapma tespit etmesi. Kontrol denkliğinin tutmaması tipik tetikleyicidir; raporun şartlı çıkmasına veya tamamlanmamış sayılmasına yol açar.",
    nerede: "Doğrulama terminolojisi; sihirbazın canlı denklik kontrolleri bunu önlemek içindir." },
  { id: "correction", en: "Correction / corrected declaration", tr: "Düzeltme / düzeltilmiş beyan", kategori: "dogrulama",
    tanim: "Beyan verildikten sonra fark edilirse beyan sahibi düzeltilmiş beyan verebilir; sertifika farkı tamamlanır veya geri alınır. Sizin tarafınızda karşılığı: " + SITE.resealPublicCopy,
    nerede: "Alıcınızdan düzeltme talebi geldiğinde izlenecek yol." },
  { id: "accreditation", en: "Accreditation", tr: "Akreditasyon", kategori: "dogrulama",
    tanim: "Doğrulayıcı kuruluşların ulusal akreditasyon kurumlarınca (Türkiye'de TÜRKAK) yetkilendirilmesi. SKDM doğrulaması yalnızca bu kapsamda akredite kuruluşlarca yapılabilir; ISO 14064 belgesi tek başına yeterli değildir.",
    nerede: "Doğrulayıcı seçerken ilk kontrol edeceğiniz belge." },
  // ── GÜMRÜK ──
  { id: "cn-code", en: "CN code (Combined Nomenclature)", tr: "CN kodu / GTİP", kategori: "gumruk",
    tanim: "AB'nin 8 haneli gümrük tarife kodu; Türkiye'deki GTİP'in ilk 8 hanesiyle aynıdır. SKDM kapsamı resmi listede " + legalFactRender("cnUniverseCount") + " benzersiz 8 haneli CN koduyla tanımlıdır — ürününüzün kapsamda olup olmadığının tek kesin ölçütü bu koddur.",
    nerede: "Gümrük beyannamesi 33. kutu; ana sayfadaki GTİP araması." },
  { id: "taric", en: "TARIC", tr: "TARIC (10 haneli AB tarife kodu)", kategori: "gumruk",
    tanim: "CN kodunun iki hane daha eklenmiş AB'ye özgü detay hali. SKDM beyanı CN düzeyinde yeterlidir; TARIC gümrük tarife ve önlem hesaplarında kullanılır.",
    nerede: "Gümrük müşavirinizin sistemleri; beyanname detayları." },
  { id: "hs-code", en: "HS code", tr: "HS kodu", kategori: "gumruk",
    tanim: "Dünya Gümrük Örgütü'nün 6 haneli uluslararası kodu; CN ve GTİP'in ortak kökü. Küresel yazışmalarda geçer, ama SKDM kapsam kontrolü 8 haneli CN ile yapılır.",
    nerede: "Uluslararası taşıma ve sigorta belgeleri." },
  { id: "origin", en: "Country of origin / installation country", tr: "Menşe ülke / üretim ülkesi", kategori: "gumruk",
    tanim: "Varsayılan değerler ülke bazlı olduğundan üretim ülkesi kritik veridir. Öncül maddenin üretim ülkesi bilinmiyorsa, o öncül için tanımlı en yüksek emisyon yoğunluklu ülkenin varsayılanı uygulanır (anti-circumvention kuralı) — 'bilmiyorum' demek pahalıya patlar.",
    nerede: "Öncül madde kayıtları; tedarikçi yazışmaları." },
  // ── ÇELİK/ÜRETİM ──
  { id: "bf-bof", en: "BF-BOF (Blast Furnace – Basic Oxygen Furnace)", tr: "Yüksek fırın – bazik oksijen fırını (entegre rota)", kategori: "celik",
    tanim: "Demir cevherinden kömür/kok ile çelik üreten entegre rota. Emisyon yoğunluğu yüksektir (tipik 1,8–2,2 tCO₂e/t); bu rotada gerçek veri her zaman avantajlı değildir — varsayılanla karşılaştırma şart.",
    nerede: "Erdemir, İsdemir, Kardemir gibi tesisler; sihirbazın rota seçimi." },
  { id: "eaf", en: "EAF (Electric Arc Furnace)", tr: "Elektrik ark ocağı", kategori: "celik",
    tanim: "Hurdanın elektrik arkıyla ergitildiği rota; Türkiye çelik üretiminin %70'inden fazlası. Emisyon yoğunluğu düşüktür (tipik 0,4–0,5 tCO₂e/t) ve Ek II gereği elektrik fiyatlanmadığından gerçek veri bu rotada genellikle belirgin avantaj sağlar.",
    nerede: "Çoğu Türk çelik ihracatçısı; 'gerçek veri mi varsayılan mı' karşılaştırması." },
  { id: "scrap", en: "Scrap", tr: "Hurda", kategori: "celik",
    tanim: "Geri kazanılmış metal girdi. SKDM'de sıfır gömülü emisyonlu sayılır ve öncül madde değildir (CN 7204 kapsam dışı). EAF tesisleri için hesabı basitleştiren asıl sebep budur.",
    nerede: "Sihirbaz 6. adımın 'hurda kullanıyorsanız bu bölüm kısa' notu." },
  { id: "dri-hbi", en: "DRI / HBI", tr: "Doğrudan indirgenmiş demir / sıcak briketlenmiş demir", kategori: "celik",
    tanim: "Doğalgazla indirgenmiş demir ara ürünü; EAF'ta hurdaya alternatif veya tamamlayıcı girdi. SKDM kapsamında öncül maddedir — tedarikçisinden SEE değeri istenir, alınamazsa varsayılan uygulanır.",
    nerede: "Sihirbaz 6. adım (hammaddeler); DRI kullanan tesisler." },
  { id: "sinter", en: "Sinter", tr: "Sinter", kategori: "celik",
    tanim: "İnce demir cevherinin yüksek fırına verilebilir boyuta getirilmesi için pişirilmiş hali. Entegre rotada önemli bir süreç emisyonu kaynağı ve öncül adayıdır.",
    nerede: "BF-BOF tesislerinin süreç kayıtları." },
  { id: "clinker", en: "Clinker", tr: "Klinker", kategori: "celik",
    tanim: "Çimentonun, kireç taşının kalsine edilmesiyle üretilen ara ürünü; çimento emisyonlarının yaklaşık üçte ikisinin kaynağı. Çimentoda dolaylı emisyon da fiyatlandığı için klinker oranı maliyeti doğrudan belirler.",
    nerede: "Çimento üreticilerinin süreç kayıtları." },
  { id: "ferro-alloys", en: "Ferro-alloys", tr: "Ferro-alaşımlar", kategori: "celik",
    tanim: "Ferro-krom, ferro-mangan gibi alaşım girdileri; SKDM kapsamında öncül maddedir. Kullanıyorsanız tedarikçiden SEE değeri istenir — EAF tesislerinde çoğu zaman tek kapsam içi girdi bunlardır.",
    nerede: "Sihirbaz 6. adım; paslanmaz çelik üreticileri." },
  { id: "npk", en: "NPK fertilisers", tr: "NPK gübreleri", kategori: "celik",
    tanim: "Azot-fosfor-potasyum içeren karma gübreler. Gübre sektöründe hem doğrudan hem dolaylı emisyon fiyatlandığından ve mark-up yalnızca %1 olduğundan maliyet profili diğer sektörlerden farklıdır.",
    nerede: "Gübre ihracatçıları; CN 3105 grubu." },
];

// ── devam: mevzuat, Türkiye, yeşil mutabakat ──
export const SOZLUK_TERIMLERI_3: SozlukTerim[] = [
  // ── MEVZUAT ──
  { id: "reg-956", en: "Regulation (EU) 2023/956", tr: "SKDM Temel Tüzüğü", kategori: "mevzuat",
    tanim: "SKDM'yi kuran ana yasal metin. Kim, ne, ne zaman sorularının cevabı burada; Omnibus (2025/2083) bu tüzüğü tadil etti.",
    nerede: "Tüm hukuki referansların kökü; rehberin dayanak sütunu." },
  { id: "ir-2547", en: "Implementing Regulation (EU) 2025/2547", tr: "Kesin dönem izleme ve raporlama tüzüğü", kategori: "mevzuat",
    tanim: "Gerçek emisyonların nasıl izlenip raporlanacağını belirleyen teknik tüzük: izleme planı, işletmeci emisyon raporu ve özet yapısı burada tanımlı. SKDMHesapla'nın 10 katmanlı veri modeli bu tüzüğe birebir oturur.",
    nerede: "Sihirbazın mimarisi; doğrulayıcınızın çalışma çerçevesi." },
  { id: "ir-2621", en: "Implementing Regulation (EU) 2025/2621", tr: "Varsayılan değerler tüzüğü", kategori: "mevzuat",
    tanim: "Ülke ve ürün bazlı varsayılan emisyon değerlerini ve mark-up takvimini (2026 +%10 / 2027 +%20 / 2028+ +%30, gübre +%1) belirleyen tüzük. Komisyon en geç Aralık 2027'de revizyon hedefliyor.",
    nerede: "Veri vermediğinizde alıcınızın ödeyeceği maliyetin kaynağı." },
  { id: "delegated-2551", en: "Delegated Regulation (EU) 2025/2551", tr: "Doğrulama tüzüğü", kategori: "mevzuat",
    tanim: "Doğrulayıcıların akreditasyonu, doğrulama kapsamı ve rapor formatını düzenleyen metin. Doğrulayıcı seçiminde ve sözleşmede referans gösterilir.",
    nerede: "Sihirbaz 7. adım; doğrulayıcı sözleşmeleri." },
  { id: "annex-i", en: "Annex I", tr: "Ek I — kapsamdaki ürün listesi", kategori: "mevzuat",
    tanim: "Tüzüğün, SKDM kapsamındaki " + legalFactRender("cnUniverseCount") + " adet 8 haneli CN kodunu saydığı ek. Kapsam sorularının tek kesin kaynağı; sektör adıyla değil kodla kontrol edilir.",
    nerede: "Ana sayfadaki GTİP aramasının dayanağı." },
  { id: "art-27a", en: "Article 27A (third-country operators' section)", tr: "Md. 27A — üçüncü ülke işletmeci bölümü", kategori: "mevzuat",
    tanim: "Registry'de üçüncü ülke üreticilerine açılan bölüm: tesisinizi ve doğrulanmış emisyon verinizi bir kez kaydedip birden çok beyan sahibiyle paylaşmanızı sağlar. Her alıcıya ayrı dosya gönderme yükünü azaltır.",
    nerede: "Birden çok AB alıcısı olan ihracatçılar için verimlilik kanalı." },
  { id: "scope-2028", en: "Downstream extension (2028 proposal)", tr: "2028 kapsam genişlemesi (taslak)", kategori: "mevzuat",
    tanim: "Aralık 2025'te kabul edilen Komisyon önerisi: 1 Ocak 2028'den itibaren yaklaşık 180 çelik ve alüminyum ağırlıklı nihai ürün (makine, araç, beyaz eşya parçaları gibi) kapsama alınacak. Henüz yasalaşmadı; izlenmeli.",
    nerede: "Makine ve otomotiv yan sanayi ihracatçılarının orta vadeli planlaması." },
  // ── TÜRKİYE ──
  { id: "tr-ets", en: "TR-ETS (Turkish ETS)", tr: "Türkiye Emisyon Ticaret Sistemi", kategori: "turkiye",
    tanim: "7552 sayılı İklim Kanunu ile kurulan ulusal sistem. Pilot dönem 2026-2027; çimento, demir-çelik, alüminyum ve gübrede 50.000 tCO₂e üzeri tesisler kapsamda ve tahsis %100 bedelsizdir — fiili karbon fiyatı ödemesi yoktur, bu yüzden SKDM mahsubu sıfırdır.",
    nerede: "Sihirbaz 8. adımdaki mahsup alanının sabit açıklaması." },
  { id: "iklim-kanunu", en: "Climate Law No. 7552", tr: "7552 sayılı İklim Kanunu", kategori: "turkiye",
    tanim: "Temmuz 2025'te yürürlüğe giren, TR-ETS'nin ve ulusal karbon fiyatlandırmasının yasal çerçevesini kuran kanun. SKDM mahsubunun Türkiye tarafındaki dayanağı.",
    nerede: "TR-ETS kapsam değerlendirmesi; mahsup görüşmeleri." },
  { id: "idb", en: "İklim Değişikliği Başkanlığı", tr: "İklim Değişikliği Başkanlığı", kategori: "turkiye",
    tanim: "TR-ETS'nin işletmecisi ulusal kurum. Pilot dönem kayıt ve raporlama yükümlülükleri bu kuruma karşıdır.",
    nerede: "TR-ETS kapsamındaki tesislerin ulusal yazışmaları." },
  { id: "epias", en: "EPİAŞ", tr: "Enerji Piyasaları İşletme A.Ş.", kategori: "turkiye",
    tanim: "TR-ETS tahsis ve ticaret altyapısının işletmecisi olması öngörülen piyasa işletmecisi.",
    nerede: "TR-ETS teknik dokümanları." },
  { id: "turkak", en: "TÜRKAK", tr: "Türk Akreditasyon Kurumu", kategori: "turkiye",
    tanim: "Doğrulayıcı kuruluşları Türkiye'de akredite edecek ulusal kurum. SKDM doğrulaması yaptırırken kuruluşun AB tanınırlıklı akreditasyonunu buradan veya muadil AB kurumlarından teyit edin.",
    nerede: "Doğrulayıcı seçimi." },
  // ── YEŞİL MUTABAKAT ──
  { id: "iso-14067", en: "ISO 14067", tr: "Ürün karbon ayak izi standardı", kategori: "yesil",
    tanim: "Bir ürünün yaşam döngüsü karbon ayak izini hesaplama standardı. SKDM kapsamı dışındaki sektörlerde alıcı taleplerinin dayandığı çerçeve budur — Kademe B tedarikçi veri dosyanızın mantığı buradan gelir.",
    nerede: "Kademe B çıktıları; SKDM dışı sektör yazışmaları." },
  { id: "csrd", en: "CSRD", tr: "Kurumsal Sürdürülebilirlik Raporlama Direktifi", kategori: "yesil",
    tanim: "Büyük AB şirketlerine Kapsam 3 dahil sürdürülebilirlik raporlaması zorunluluğu getiren direktif. Alıcınız SKDM kapsamı dışında olsanız bile sizden karbon verisi istiyorsa sebebi çoğu zaman budur.",
    nerede: "Kademe B taleplerinin yasal kökeni." },
  { id: "scope-3", en: "Scope 3 emissions", tr: "Kapsam 3 emisyonları", kategori: "yesil",
    tanim: "Bir şirketin değer zincirindeki dolaylı emisyonlar; satın aldığı ürünlerin üretim emisyonu buna girer. Alıcınızın Kapsam 3 hesabına sizin ürününüzün ayak izi girdi olur.",
    nerede: "CSRD raporlaması; Kademe B dosyanızın kullanım yeri." },
  { id: "eudr", en: "EUDR", tr: "AB Ormansızlaşma Tüzüğü", kategori: "yesil",
    tanim: "Soya, kahve, kakao, palm yağı, kauçuk, sığır ve ahşap bazlı ürünlerde ormansızlaşmasız tedarik kanıtı isteyen tüzük. Gıda ve tarım ihracatçılarının SKDM'den ayrı izlemesi gereken düzenleme.",
    nerede: "Kademe B 'Gıda & Tarım' sektörü." },
  { id: "ppwr", en: "PPWR", tr: "Ambalaj ve Ambalaj Atığı Tüzüğü", kategori: "yesil",
    tanim: "AB pazarına sunulan ambalajlara geri dönüştürülmüş içerik ve geri dönüşüm yükümlülükleri getiren tüzük. Ambalaj ihracatçılarının karbon verisinin yanında izleyeceği ikinci düzenleme.",
    nerede: "Kademe B 'Ambalaj' sektörü." },
  { id: "dpp", en: "ESPR / DPP (Digital Product Passport)", tr: "Dijital Ürün Pasaportu", kategori: "yesil",
    tanim: "Ürünlerin malzeme, tamir edilebilirlik ve çevresel verilerini dijital kimlikle taşımasını öngören çerçeve. Önce pil tüzüğünde (2027'den itibaren) somutlaşıyor; tekstil ve elektronik sırada.",
    nerede: "Kademe B 'Batarya', 'Tekstil', 'Elektronik' sektörleri." },
  { id: "battery-reg", en: "Battery Regulation (EU) 2023/1542", tr: "AB Pil Tüzüğü", kategori: "yesil",
    tanim: "Piller için karbon ayak izi beyanı, geri dönüştürülmüş içerik oranı ve pil pasaportu zorunlulukları getiren tüzük. Batarya ihracatçısının SKDM'den bağımsız ana uyum gündemi.",
    nerede: "Kademe B 'Batarya ve Pil' sektörü." },
];

export const SOZLUK_TERIMLERI_ALL: SozlukTerim[] = [
  ...SOZLUK_TERIMLERI,
  ...SOZLUK_TERIMLERI_2,
  ...SOZLUK_TERIMLERI_3,
];

// ── rehberin bağlantı verdiği ek maddeler ──
export const SOZLUK_TERIMLERI_EK: SozlukTerim[] = [
  { id: "importer", en: "Importer", tr: "İthalatçı (alıcınız)", kategori: "taraflar",
    tanim: "Ürününüzü AB'ye ithal eden taraf. 50 ton üzeri kapsam-içi ithalat yapıyorsa yetkili beyan sahibi olmak, yıllık beyan vermek ve sertifika teslim etmek zorundadır. Sertifika maliyetini taşıyan taraf budur — siz değilsiniz.",
    nerede: "Ticari sözleşmeleriniz; 'kim ödüyor?' sorusunun cevabı." },
  { id: "muhur", en: "SHA-256 digital seal", tr: "SHA-256 dijital mühür", kategori: "sablon",
    tanim: "Dosya paketinizin içeriğinden matematiksel olarak üretilen benzersiz imza. İçerikte bir harf bile değişse imza değişir; /dogrula/ sayfasından herkes paketin özgünlüğünü teyit edebilir. Mühür dosyaya özeldir, başka dosyaya devredilemez.",
    nerede: "Mühürlü paketinizin manifest dosyası; /dogrula/ sayfası." },
  { id: "cbam-accreditation-guidance-2026", en: "CBAM verification and accreditation guidance", tr: "CBAM doğrulayıcı ve akreditasyon rehberi (24 Ağustos 2026)", kategori: "dogrulama",
    tanim: "Avrupa Komisyonu'nun 24 Ağustos 2026'da yayımladığı, CBAM kesin döneminde görev yapacak doğrulayıcılar ve Ulusal Akreditasyon Kuruluşlarının rollerini detaylandıran resmi rehber. Akredite doğrulayıcıların CBAM Registry kayıt ve erişim süreci 1 Eylül 2026'dan önce başlamaz; doğrulayıcıların akreditasyon aldıktan sonra iki ay içinde (ancak 1 Eylül'den önce olmamak üzere) Registry'ye kaydolmaları gerekir. İlk doğrulama raporları 2027 Ocak ayından itibaren 2026 emisyonları için Registry üzerinden düzenlenecektir.",
    nerede: "Avrupa Komisyonu DG TAXUD resmi duyurusu; doğrulayıcı ve akreditasyon kuruluşu ilişkilerinde." },
  { id: "cbam-registry-declarants-portal-2026", en: "CBAM Registry Declarants Portal user manual", tr: "CBAM Registry Declarants Portal kılavuzu (21 Ağustos 2026)", kategori: "sablon",
    tanim: "Komisyonun 21 Ağustos 2026'da yayımladığı, CBAM Kayıt Sistemi (Registry) ve Beyan Sahibi Portalı'nın (Declarants Portal) operasyonel kullanımını açıklayan resmi teknik kılavuz. Tesis adı ve şirket kayıt numarası gibi bilgilerin Registry kayıtlarıyla tam uyumlu girilmesini hedefler.",
    nerede: "Avrupa Komisyonu CBAM Registry portalı; beyan işlemleri sırasında." },
  { id: "definitive-period-guidance-2026", en: "Definitive period guidance documents", tr: "Kesin Dönem Rehberleri (14 Ağustos 2026)", kategori: "mevzuat",
    tanim: "Avrupa Komisyonu'nun 14 Ağustos 2026'da yayımladığı, 1 Ocak 2026'dan itibaren geçerli kesin dönem hazırlıkları (actual values, monitoring plan, gömülü emisyon hesabı, varsayılan değerler ve free allocation adjustment) için 4 genel ve 6 sektörel (5a-5f) rehber paketi.",
    nerede: "Avrupa Komisyonu CBAM resmi mevzuat ve rehberlik kütüphanesi." },
  { id: "corrected-default-values-2026", en: "Corrected default values dataset", tr: "Düzeltilmiş Varsayılan Değerler (10 Ağustos 2026)", kategori: "emisyon",
    tanim: "Implementing Regulation (EU) 2025/2621 tüzüğünün (EU) 2026/1740 ile yapılan düzeltmelerini yansıtan ve Komisyon tarafından 10 Ağustos 2026 tarihinde güncellenen resmi varsayılan emisyon değerleri veri seti.",
    nerede: "Avrupa Komisyonu CBAM varsayılan değerler veri tabanı ve Excel kiti." },
];

export const SOZLUK_TERIMLERI_FINAL: SozlukTerim[] = [
  ...SOZLUK_TERIMLERI_ALL,
  ...SOZLUK_TERIMLERI_EK,
];
